version: '3'

services:
  postgresSQL:
    image: postgres:9.3.20-alpine
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - /home/docker/database/PostgreSQL:/var/lib/postgresql/data
    networks:
      - docker-local-network
      
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "raul.coan@locaweb.com.br"
      PGADMIN_DEFAULT_PASSWORD: "pgadmin"
    ports:
      - "6543:80"
    depends_on:
      - postgresSQL
    networks:
      - docker-local-network

networks: 
  docker-local-network:
    driver: bridge