version: '3'

services:
  postgresSQL:
    image: postgres:9.3.20-alpine
    container_name: docker-local-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
    networks:
      - docker-local-network
      
  pgadmin:
    image: dpage/pgadmin4
    container_name: docker-local-postgres-admin
    environment:
      PGADMIN_DEFAULT_EMAIL: "raul.coan@locaweb.com.br"
      PGADMIN_DEFAULT_PASSWORD: "pgadmin"
    ports:
      - "6543:80"
    depends_on:
      - postgresSQL
    networks:
      - docker-local-network

networks: 
  docker-local-network:
    driver: bridge