version: '3'

services:
  redis:
    image: redis:2.8
    container_name: docker-local-redis
    volumes:
      - /var/lib/redis/data
    ports:
    - "6379:6379"
    networks:
      - docker-local-network

networks: 
  docker-local-network:
    driver: bridge
